# Generated by Django 5.2.1 on 2025-06-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('days', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('recommended_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('activity', models.TextField(blank=True)),
                ('lodging', models.TextField(blank=True)),
                ('dining', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itineraries.itinerary')),
            ],
        ),
    ]
